---
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Corunet Challenge Game Server
  description: Test File for SCC MultiApi Plugin.
  contact:
    name: Corunet
    url: coru.net
    email: info@coru.net
  license:
    name: MIT
servers:
- url: http://localhost:8080/v1
paths:
  /games:
    summary: Hola
    post:
      summary: Start a Game
      operationId: createGame
      description: Test File for SCC MultiApi Plugin.
      tags:
      - games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewGame"
      responses:
        '200':
          description: New game created;
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewGamePlay"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: List all available games
      description: Test File for SCC MultiApi Plugin.
      tags:
      - games
      operationId: listGames
      responses:
        '200':
          description: A paged array of games
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /games/{gameId}:
    get:
      parameters:
      - name: gameId
        in: query
        required: true
        description: The id of the game to retrieve
        schema:
          type: integer
          format: int32
      summary: Info for a specific game
      operationId: getGamesByGameId
      description: Test Description for SCC multiApi Converter
      tags:
      - games
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameInfo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Game:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    GameInfo:
      type: object
      required:
      - gameName
      - players
      - rooms
      properties:
        rooms:
          type: integer
          format: int32
        gameName:
          type: string
        players:
          type: array
          items:
            type: string
    NewGame:
      type: object
      required:
      - gameId
      - playerName
      properties:
        gameId:
          type: integer
          format: int32
        playerName:
          type: string
    NewGamePlay:
      type: object
      required:
      - gameId
      - gameName
      - roomId
      properties:
        gameId:
          type: integer
          format: int32
        gameName:
          type: string
        roomId:
          type: integer
          format: int32
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
tags:
- name: games
  description: Test description for SCC MultiApi Plugin.
