name: Java CI with Maven (PR)

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review, review_requested ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check if version is updated
      uses: avides/actions-project-version-check@v1.3.0
      id: actions_project_version_check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: pom.xml
      continue-on-error: true
    - name: Versioning specifications
      if: ${{ job.check-version.actions_project_version_check.status }} == 'failure'
      run: |
        echo "::warning::To update your version, you should use https://semver.org specifications"
        exit 1
    - name: New software version
      if: ${{ job.check-version.actions_project_version_check.status }} == 'failure'
      run: echo "New software version is " ${{ steps.actions_project_version_check.outputs.version }}
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
